if(!("MBX"in window)){MBX={};}
MBX.EventHandler=(function(){var self={};self.isIE=Prototype.Browser.IE;self.EventBox=(function(){var self={};self.isIE=Prototype.Browser.IE;var browserLikeEventExtender={preventDefault:function(){},stopPropagation:function(){},pageX:0,pageY:0,clientX:0,clientY:0};var CustomEvent=function(theTarget,evt,opts){this.type=evt;this.target=theTarget;this.srcElement=theTarget;this.eventName=evt;this.memo={};Object.extend(this,opts);for(prop in browserLikeEventExtender){if(browserLikeEventExtender.hasOwnProperty(prop)){if(!this[prop]){this[prop]=browserLikeEventExtender[prop];}}}
if(self.isIE){Event.extend(this);}};if(self.isIE){(function(){var methods=Object.keys(Event.Methods).inject({},function(m,name){m[name]=Event.Methods[name].methodize();return m;});CustomEvent.prototype=CustomEvent.prototype||document.createEvent("HTMLEvents").__proto__;Object.extend(CustomEvent.prototype,methods);})();}
self.buildCustomEvent=function(theTarget,evt,opts){var evt=new CustomEvent(theTarget,evt,opts);return Event.extend(evt);};var ieSubscribe=function(elem,type,func){var handler=function(evt){Event.extend(evt);func(evt);};return elem.attachEvent("on"+type,func);};var captureSubscribe=function(elem,type,func){return elem.addEventListener(type,func,true);};self.subscribe=function(elem,type,func,opts){opts=opts||{};if(opts.ieOnly){return ieSubscribe(elem,type,func);}
if(opts.capture){return captureSubscribe(elem,type,func);}
return $(elem).observe(type,func);};self.elementFromEvent=function(evt){var targ;if(!evt){var e=window.event;}
if(evt.target){targ=evt.target;}else{if(evt.srcElement){targ=evt.srcElement;}}
if(targ.nodeType==3){targ=targ.parentNode;}
return targ;};self.subscribeToDomReady=function(func){document.observe("dom:loaded",func);};return self;})();var stdEvents=["click","mouseout","mouseover","keypress","change"];var ieFocusBlurEvents=["focusin","focusout"];var nonBubblingBlurFocusEvents=["blur","focus"];var eventListeners={};var isArray=function(object){return object!=null&&typeof object=="object"&&'splice'in object&&'join'in object;};var makeArray=function(obj){if(!isArray(obj)){return[obj];}else{return obj;}};var eachElement=function(ary,func){ary=ary||{};ary=makeArray(ary);var len=ary.length;for(var i=0;i<len;++i){func(ary[i]);}};var normalizeEventType=function(evtType){if(!(/focusin|focusout/.test(evtType))){return evtType;}else{switch(evtType){case"focusin":return"focus";break;case"focusout":return"blur";break;}}};var handleEvent=function(evt){var targetElement;if(evt){var evtType=normalizeEventType(evt.type);try{targetElement=self.EventBox.elementFromEvent(evt);}catch(e){}
if(targetElement){functionsFromElementAndEvent(targetElement,evt,{eventType:evtType});}}};eachElement(stdEvents,function(evtType){eventListeners[evtType]=self.EventBox.subscribe(document,evtType,handleEvent);});if(!self.isIE){eachElement(nonBubblingBlurFocusEvents,function(evtType){eventListeners[evtType]=self.EventBox.subscribe(document,evtType,handleEvent,{capture:true});});}else{eachElement(ieFocusBlurEvents,function(evtType){eventListeners[evtType]=self.EventBox.subscribe(document,evtType,handleEvent,{ieOnly:true});});}
var domReadyAlreadyFired=false;self.EventBox.subscribeToDomReady(function(){domReadyAlreadyFired=true;MBX.EventHandler.fireCustom(document,"dom:loaded");});var subscriptions={ids:{},classes:{},rules:{},objects:{}};var subscriptionMarker=1;var callFunctions=function(functionsToCall,evt){while(functionsToCall.length>0){functionsToCall.pop()(evt);}};var wrap=function(func,wrapper){var __method=func;__method.bind=function(){if(arguments.length<2&&Object.isUndefined(arguments[0]))return this;var __method=this,args=Array.prototype.slice.call(arguments),object=args.shift();return function(){return __method.apply(object,args.concat(Array.prototype.slice.call(arguments)));}};return function(){return wrapper.apply(this,[__method.bind(this)].concat(Array.prototype.slice.call(arguments)));}};var deferFunctions=function(functionsToCall,evt){var func;while(functionsToCall.length>0){func=wrap(functionsToCall.pop(),function(orig){orig(evt);});setTimeout(func,0);}};var callFunctionsFromRules=function(target,evtType,evt){if(!subscriptions.rules[evtType]){return;}
var subscriptionsToCall=[];for(prop in subscriptions.rules[evtType]){if(subscriptions.rules[evtType].hasOwnProperty(prop)&&target.match(prop)){subscriptionsToCall=subscriptionsToCall.concat(subscriptions.rules[evtType][prop]);}}
eachElement(subscriptionsToCall,function(sub){sub.callFunctions(evt);});};var callFunctionsFromIdOrObject=function(specifierType,targetId,evtType,evt){var returnArray=[];var deferArray=[];var subscriptionTarget=subscriptions[specifierType][targetId];if(subscriptionTarget&&subscriptionTarget[evtType]){returnArray=returnArray.concat(subscriptionTarget[evtType]);}
eachElement(returnArray,function(sub){sub.callFunctions(evt);});};var callFunctionsFromClasses=function(targetClasses,evtType,evt){var subscriptionsToCall=[];var functionsToDefer=[];var classObject;for(var index=0,classLen=targetClasses.length;index<classLen;++index){classObject=subscriptions.classes[targetClasses[index]];if(classObject&&classObject[evtType]){subscriptionsToCall=subscriptionsToCall.concat(classObject[evtType]);}}
eachElement(subscriptionsToCall,function(sub){sub.callFunctions(evt);});};var functionsFromElementAndEvent=function(targetElement,evt,opts){if(!targetElement){return;}
opts=opts||{};var evtType;if(opts.eventType){evtType=opts.eventType;}else{evtType=evt.type;}
if(targetElement.__MotionboxEventHandlerMaker){callFunctionsFromIdOrObject("objects",targetElement.__MotionboxEventHandlerMaker,evtType,evt);if(!Object.isElement(targetElement)){return;}}
if(targetElement.id){callFunctionsFromIdOrObject("ids",targetElement.id,evtType,evt);}
if(targetElement.className){var targetClasses=targetElement.className.split(" ");callFunctionsFromClasses(targetClasses,evtType,evt);}
callFunctionsFromRules(targetElement,evtType,evt);if(targetElement!=window&&targetElement!=document&&targetElement.parentNode){var upTreeNode=targetElement.parentNode;if(upTreeNode&&upTreeNode.tagName&&upTreeNode.tagName!="HTML"){functionsFromElementAndEvent(upTreeNode,evt,opts);}}};var isId=function(specifierString){return/^\#[\w-]+$/.test(specifierString);};var isClass=function(specifierString){return/^\.[\w-]+$/.test(specifierString);};var isObject=function(specifier){return typeof specifier=="object";};var getSubscriptionMarker=function(obj){if(!obj.__MotionboxEventHandlerMaker){obj.__MotionboxEventHandlerMaker=subscriptionMarker++;}
return obj.__MotionboxEventHandlerMaker;};if(self.isIE){var destroyObservers=function(){stdEvents.each(function(evtType){document.stopObserving(evtType,handleEvent);});};window.attachEvent('onbeforeunload',destroyObservers);}
var Subscription=function(specifier,eventType,funcs,opts){funcs=makeArray(funcs);this.specifier=specifier;this.eventType=eventType;this.funcs=funcs;this.opts=opts||{};this.calculateSpecifierType();this.cache();return this;};Subscription.prototype={callFunctions:function(evt){if(this.opts.defer){deferFunctions(this.funcs,evt);}else{callFunctions(this.funcs,evt);}},calculateSpecifierType:function(){if(isObject(this.specifier)){this.specifierType="objects";this.specifier=getSubscriptionMarker(this.specifier);}else{if(typeof this.specifier!="string"){throw new Error("specifier was neither an object nor a string");}
if(isId(this.specifier)){this.specifier=this.specifier.sub(/#/,"");this.specifierType="ids";}
if(isClass(this.specifier)){this.specifierType="classes";this.specifier=this.specifier.sub(/\./,"");}
if(!this.specifierType){this.specifierType="rules";}}},_cacheForRules:function(){if(!subscriptions.rules[this.eventType]){subscriptions.rules[this.eventType]={};}
var specifierObject=subscriptions.rules[this.eventType];if(!specifierObject[specifier]){specifierObject[specifier]=[];}
specifierObject[specifier].push(this);},cache:function(){if(this.specifierType=="rules"){this._cacheForRules();}else{if(!subscriptions[this.specifierType][this.specifier]){subscriptions[this.specifierType][this.specifier]={};}
var specifierObject=subscriptions[this.specifierType][this.specifier];if(!specifierObject[this.eventType]){specifierObject[this.eventType]=[];}
specifierObject[this.eventType].push(this);}},_uncacheForRules:function(){var specifierObject=subscriptions.rules[this.eventType];specifierObject.splice(specifierObject.indexOf(this),1);},uncache:function(){if(this.specifierType=="rules"){this._uncacheForRules();}else{var specifierObject=subscriptions[this.specifierType][this.specifier][this.eventType];specifierObject.splice(specifierObject.indexOf(this),1);}}};var SubscriptionSet=function(specifiers,evtTypes,funcs,opts){specifiers=makeArray(specifiers);evtTypes=makeArray(evtTypes);this.specifiers=specifiers;this.evtTypes=evtTypes;this.funcs=funcs;this.opts=opts||{};this.subscriptions=[];this.createSubscriptions();return this;};SubscriptionSet.prototype={createSubscriptions:function(){for(var i=0;i<this.specifiers.length;++i){for(var j=0;j<this.evtTypes.length;++j){this.subscriptions.push(new Subscription(this.specifiers[i],this.evtTypes[j],this.funcs,this.opts));}}},unsubscribe:function(){eachElement(this.subscriptions,function(subscription){subscription.uncache();});}};self.subscribe=function(specifiers,evtTypes,funcs,opts){return new SubscriptionSet(specifiers,evtTypes,funcs,opts);},self.unsubscribe=function(handlerObject){handlerObject.unsubscribe();},self.fireCustom=function(theTarget,evt,opts){if(theTarget){opts=opts||{};if(Object.isElement(theTarget)){var theEvent=self.EventBox.buildCustomEvent(theTarget,evt,opts);handleEvent(theEvent);}else{callFunctionsFromIdOrObject("objects",getSubscriptionMarker(theTarget),evt,opts);}}},self.onDomReady=function(funcs,opts){opts=opts||{};if(typeof opts.defer=='undefined'){opts.defer=true;}
funcs=makeArray(funcs);if(domReadyAlreadyFired){if(opts.defer){deferFunctions(funcs,"dom:loaded");}else{callFunctions(funcs,"dom:loaded");}}else{return MBX.EventHandler.subscribe(document,"dom:loaded",funcs,{defer:opts.defer});}},self.dirSubscriptions=function(){console.dir(subscriptions);},self.dirEventListeners=function(){console.dir(eventListeners);},self.debugSubscriptions=function(){return subscriptions;}
return self;})();
